"""Optional Slurm array rendering over the ordinary ``run --job`` interface."""
from __future__ import annotations

import json
import os
import re
import shlex
import sys
from pathlib import Path

from . import plan as planmod
from .execution_profiles import resolve_profile
from .plan import RunError
from .spec import SpecError


def export_slurm(
    study_dir: str | Path,
    out_path: str,
    *,
    profile: str | Path | None = None,
    partition: str | None = None,
    time: str | None = None,
    job_name: str | None = None,
    exclusive: bool | None = None,
    account: str | None = None,
    qos: str | None = None,
    cpus_per_task: int | None = None,
    memory: str | None = None,
    max_concurrent: int | None = None,
) -> str:
    """Write a script without submitting; resources default to site defaults.

    Explicit keyword arguments override the profile. None means unspecified;
    exclusive=False explicitly removes an inherited exclusive allocation.
    """
    resources = resolve_profile(
        profile, partition=partition, time=time, exclusive=exclusive, account=account,
        qos=qos, cpus_per_task=cpus_per_task, memory=memory, max_concurrent=max_concurrent,
    )
    manifest = planmod.load_manifest(study_dir)
    study_abs = str(Path(study_dir).absolute())
    if job_name is not None and (
        not isinstance(job_name, str) or not job_name.strip()
        or any(ord(char) < 32 or ord(char) == 127 for char in job_name)
    ):
        raise SpecError("slurm job_name must be nonempty and contain no control characters")
    name = re.sub(r"[^A-Za-z0-9_.-]", "_", job_name or manifest["study_name"])
    if name.startswith("-"):
        name = "_" + name[1:]
    if not manifest["jobs"]:
        raise RunError("cannot export an empty Slurm array")
    repo = manifest["repo_root"]
    sim = manifest["simulator_root"]
    directives = []
    for key, directive in (
        ("partition", "partition"), ("account", "account"), ("qos", "qos"),
        ("time", "time"), ("cpus_per_task", "cpus-per-task"), ("memory", "mem"),
    ):
        if key in resources:
            directives.append(f"#SBATCH --{directive}={resources[key]}")
    if resources.get("exclusive", False):
        directives.append("#SBATCH --exclusive")
    array = f"0-{len(manifest['jobs']) - 1}"
    if "max_concurrent" in resources:
        array += f"%{resources['max_concurrent']}"
    directives.extend([
        f"#SBATCH -J {name}", f"#SBATCH --array={array}",
        "#SBATCH --output=slurm-%A_%a.out", "#SBATCH --error=slurm-%A_%a.out",
    ])
    metadata = {
        "effective_profile": resources,
        "profile_path": str(Path(profile).absolute()) if profile is not None else None,
        "python": sys.executable,
        "study_dir": study_abs,
        "plan_hash": manifest["_plan_hash"],
        "job_name": name,
    }
    script = (
        "#!/bin/bash\n"
        + "\n".join(directives) + "\n"
        "# Generated by glucoalg.tuning export-slurm. Review, then submit by hand:\n"
        "#   sbatch <this-script>\n"
        "# This tool never submits by itself.\n"
        "# Execution metadata: " + json.dumps(metadata, sort_keys=True) + "\n"
        "set -euo pipefail\n"
        'test -n "${SLURM_ARRAY_TASK_ID:-}" || { echo "missing SLURM_ARRAY_TASK_ID" >&2; exit 2; }\n'
        "export JAX_PLATFORMS=cpu\n"
        "export JAX_PLATFORM_NAME=cpu\n"
        'export CUDA_VISIBLE_DEVICES=""\n'
        f"export PYTHONPATH={shlex.quote(repo + os.pathsep + sim)}\n"
        # Python's current directory precedes PYTHONPATH. Start in the sealed
        # checkout so a different submission directory cannot shadow its code.
        f"cd {shlex.quote(repo)}\n"
        'echo "node=$(hostname) date=$(date -u +%FT%TZ)"\n'
        f"echo \"repo_head=$(git -C {shlex.quote(repo)} rev-parse HEAD)\"\n"
        f"echo \"sim_head=$(git -C {shlex.quote(sim)} rev-parse HEAD)\"\n"
        f"exec {shlex.quote(sys.executable)} - {shlex.quote(study_abs)} <<'ARRAY_EOF'\n"
        "import os, sys\n"
        "from glucoalg.tuning.plan import load_manifest, probe_sources\n"
        "from glucoalg.tuning.execute import check_source_provenance\n"
        "from glucoalg.runtime import initialize_simulator\n"
        "manifest = load_manifest(sys.argv[1])\n"
        "check_source_provenance(manifest, probe_sources(manifest['simulator_root'], manifest['repo_root']))\n"
        "try:\n"
        "    index = int(os.environ['SLURM_ARRAY_TASK_ID'])\n"
        "except ValueError:\n"
        "    raise SystemExit('invalid SLURM_ARRAY_TASK_ID')\n"
        "if not 0 <= index < len(manifest['jobs']):\n"
        "    raise SystemExit('invalid SLURM_ARRAY_TASK_ID')\n"
        "initialize_simulator(manifest['simulator_root'])\n"
        "import jax, torch\n"
        "assert not torch.cuda.is_available(), 'CUDA visible'\n"
        "assert all(device.platform == 'cpu' for device in jax.devices()), 'JAX is not on CPU'\n"
        "job_id = manifest['jobs'][index]['job_id']\n"
        "os.execv(sys.executable, [sys.executable, '-m', 'glucoalg.tuning', 'run',\n"
        "    '--plan', sys.argv[1], '--job', job_id, '--resume'])\n"
        "ARRAY_EOF\n"
    )
    out = Path(out_path)
    protected = {
        (Path(study_abs) / filename).resolve()
        for filename in (planmod.MANIFEST_NAME, planmod.MANIFEST_HASH_NAME,
                         planmod.SPEC_NAME, planmod.PREREG_NAME, planmod.LEDGER_NAME)
    }
    if out.resolve() in protected:
        raise SpecError("Slurm output must not overwrite study metadata")
    try:
        out.write_text(script, encoding="utf-8")
    except OSError as exc:
        raise RunError(f"cannot write Slurm script {out}: {exc}") from exc
    return out_path
